TestCase - bug in XML encoding line returns chr(10).
zendframework/zend-problem-details pull request #46
Opened 2019-01-02 10:33 UTC by ncou

Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [ ] Is this related to documentation?

2019-01-07 21:47 UTC, weierophinney commented
@ncou — it looks like you and @webimpress have agreed on a way to fix this in #45; will you be updating the patch with the fixed regular expression and/or `str_replace` statements?

2019-01-08 12:01 UTC, ncou commented
Hi, yes i will update the code with the fix (using str_replace).

2019-01-08 12:04 UTC, ncou commented
It should be fine now. @weierophinney can you check ?

2019-01-08 12:37 UTC, michalbundyra requested changes

2019-01-08 12:37 UTC, webimpress commented on src/ProblemDetailsResponseFactory.php
> +            $key = str_replace(chr(10), '_', $key);
I would use here `"\n"` instead. It is more clear than `chr(10)`.

2019-01-08 14:28 UTC, ncou commented on src/ProblemDetailsResponseFactory.php
> +            $key = str_replace(chr(10), '_', $key);
I made the change.

2019-01-08 14:48 UTC, michalbundyra approved these changes
LGTM 👍

2019-01-09 14:14 UTC, merged

2019-01-09 14:15 UTC, weierophinney commented
Thanks, @ncou!