Added ExceptionInterface as marker for package-specific exception
zendframework/zend-problem-details pull request #8
Opened 2017-10-03 21:36 UTC by webimpress

All exceptions thrown in the repository should implement that interface.
Added suffix "Trait" and "Interface" to exception traits and interfaces.

2017-10-05 21:27 UTC, weierophinney requested changes
I have one concern, and it's a big one: the `ProblemDetailsExceptionInterface` SHOULD NOT extend the package `ExceptionInterface`, which I detail more in a comment below.

2017-10-05 21:27 UTC, weierophinney commented on src/Exception/ProblemDetailsExceptionInterface.php
> +interface ProblemDetailsExceptionInterface extends ExceptionInterface, JsonSerializable
This interface should not extend the package marker interface; it's intended for _consumers_ to implement, and, as such, will fall within their own package inheritance.

The `ExceptionInterface` marker is for identifying which exceptions _are thrown by this package_.

2017-10-05 21:30 UTC, weierophinney commented
@webimpress Don't forget to update the docs as well; I noticed it first in those. :smile:

2017-10-05 21:37 UTC, webimpress commented
@weierophinney All updated right now 😄
Rebased to resolve conflicts.

2017-10-09 13:30 UTC, weierophinney approved these changes

2017-10-09 13:45 UTC, merged

2017-10-09 13:46 UTC, weierophinney commented
Thanks, @webimpress